KarateIsere/KarateIsere/Models/CompetitionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KarateIsere.DataAccess;
using KarateIsere.DataAccess.Tool;
using Model=KarateIsere.DataAccess;

namespace KarateIsere.Models {
    public class CompetitionViewModel : Model.Competition {
        public IEnumerable<SelectListItem> CategorieList {
            get {
                //Enlève les catégories déjà sélectionnées de la liste des catégories
                List<String> cateList = Model.Categorie.GetAll().Select( d => d.Nom ).ToList();
                cateList.RemoveAll( d => SelectedCategorie.Contains( d ) );

                return cateList.Select( d =>
                                new SelectListItem {
                                    Value = d,
                                    Text = d
                                } );

            }
        }

        private List<string> selectedCategorie;

        public List<string> SelectedCategorie {
            get {
                if (Categorie != null && Categorie.Count > 0) {
                    selectedCategorie =  Categorie.Select( d => d.Nom ).ToList();
                }

                if (selectedCategorie == null) {
                    selectedCategorie = new List<string>();
                }

                return selectedCategorie;
            }
        }

        public override void Create () {
            //on a besoins de faire cette manipulation car CompetitionViewModel hérite
            //de Competition mais ne possède pas d'information de mappage pour Entity Framework
            Competition c = this;
            (c as Competition).Create();
        }

        public override void Update () {
            //on a besoins de faire cette manipulation car CompetitionViewModel hérite
            //de Competition mais ne possède pas d'information de mappage pour Entity Framework
            Competition c = (Competition) this;
            c.Update();
        }

        /// <summary>
        /// Methode utilisée pour mapper le type proxy compétition sur l'objet compétition view model
        /// </summary>
        /// <param name="competitions"></param>
        /// <returns></returns>
        public static List<CompetitionViewModel> ToCompetitionViewModel ( List<Competition> competitions ) {
            List<CompetitionViewModel> res = new List<CompetitionViewModel>();

            foreach (Competition c in competitions) {
                CompetitionViewModel obj = new CompetitionViewModel();
                Mapper.Map( c, obj );
                res.Add( obj );
            }

            return res;
        }

    }
}

KarateIsere/KarateIsere/Areas/Private/Controllers/CompetitionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Web;
using System.Web.Mvc;
using KarateIsere.DataAccess;
using KarateIsere.DataAccess.Tool;
using KarateIsere.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NLog;

namespace KarateIsere.Areas.Private.Controllers {
    [Authorize(Roles = "Admin")]
    public class CompetitionsController : Controller {

        private static Logger logger = LogManager.GetCurrentClassLogger();

        // GET: Private/Competitions
        public ActionResult Index() {
            List<Competition> compets = new List<Competition>();
            try {
                compets = GetCompetitions();
            }
            catch (Exception e) {
                logger.Error(e);
            }

            return View(GetCompetitions());
        }

        // GET: Private/Competitions/Details/5
        public ActionResult Details(int id) {
            List<Competiteur> c = new List<Competiteur>();
            try {
                c = Inscriptions.GetInscriptions(id);
                ViewBag.CompetId = id;


            }
            catch (Exception e) {
                logger.Error(e);
            }

            return View(c);
        }

        /// <summary>
        /// Exporte une compétition vers excel
        /// </summary>
        /// <param name="id">Compétition Id</param>
        /// <returns></returns>
        [HttpGet]
        public FileStreamResult Export(int id) {

            FileStreamResult res = null;

            try {
                Competition compet = Competition.GetById(id);
                List<Competiteur> competiteurs = Inscriptions.GetInscriptions(id);
                string delimChar = ";";
                //Si je ferme moi-même les stream l'application crash
                //il semble que le framework les ferme lui-même
                MemoryStream output = new MemoryStream();
                StreamWriter writer = new StreamWriter(output, Encoding.UTF8);

                //headers
                writer.Write("Club");
                writer.Write(delimChar);
                writer.Write("Catégorie");
                writer.Write(delimChar);
                writer.Write("NumLicence");
                writer.Write(delimChar);
                writer.Write("Nom");
                writer.Write(delimChar);
                writer.Write("Prenom");
                writer.Write(delimChar);
                writer.Write("Poids");
                writer.WriteLine();

                //Content
                foreach (Competiteur c in competiteurs) {
                    writer.Write(c.Club.NomClub);
                    writer.Write(delimChar);
                    writer.Write(c.Categorie.Nom);
                    writer.Write(delimChar);
                    writer.Write(c.NumLicence);
                    writer.Write(delimChar);
                    writer.Write(c.Nom);
                    writer.Write(delimChar);
                    writer.Write(c.Prenom);
                    writer.Write(delimChar);
                    writer.Write(c.Poids);
                    writer.WriteLine();
                }

                writer.Flush();
                output.Position = 0;

                res = this.File(output,
                            "application/vnd.ms-excel",
                             compet.Nom + "_" + compet.DateCompetition.ToShortDateString() + ".csv");
            }
            catch (Exception e) {
                logger.Error(e);
            }

            return res;
        }

        [HttpPost]
        public ActionResult Create(Competition compet) {
            List<Competition> compets = new List<Competition>();
            try {
                DateTime competDate = compet.DateCompetition;
                DateTime finInscription = compet.FinInscription;

                if (competDate.CompareTo(finInscription) <= 0) {
                    ModelState.AddModelError("DateCompetition",
                                        "La date de la compétition doit être " +
                                        "supérieur à la date de fin d'inscription");
                }

                if (ModelState.IsValid) {
                    compet.Categorie = (List<Categorie>) Session["selectedCategorie"];
                    compet.Create();
                    Session.Remove("selectedCategorie");
                }

                compets = GetCompetitions();
            }
            catch (Exception e) {
                logger.Error(e);
            }

            return View("Index", compets);
        }

        // GET: Private/Competitions/Edit/5
        public ActionResult Edit(int competId) {
            Competition c = new Competition(); ;
            try {
                c = Competition.GetById(competId);

                //Liste des catégories déjà enregistrées
                List<Categorie> listCate = c.Categorie.ToList();
                Session["selectedCategorie"] = listCate;
                List<string> cate = GetCateList(listCate);
                ViewBag.CateList = cate;
            }
            catch (Exception e) {
                logger.Error(e);
            }

            return View(c);
        }

        // POST: Private/Competitions/Edit/5
        [HttpPost]
        public ActionResult Edit(Competition compet) {
            try {
                if (ModelState.IsValid) {
                    compet.Categorie = (List<Categorie>) Session["selectedCategorie"];
                    compet.Update();
                    Session.Remove("selectedCategorie");
                    return View("Index", GetCompetitions());
                }

                return View("Edit", compet);
            }
            catch (Exception e) {
                logger.Error(e);
                return View();
            }
        }

        public ActionResult Delete(int competId) {
            try {
                Competition c = Competition.GetById(competId);

                if (c != null) {
                    c.Delete();
                }

                return View("Index", GetCompetitions());
            }
            catch (Exception e) {
                logger.Error(e);
                return View();
            }
        }

        /// <summary>
        /// Ajoute une catégorie dans la variable de session qui sera
        /// utilisée pour la création de la compétition
        /// </summary>
        /// <param name="name">Catégorie à ajouter</param>
        public void AddCategorie(string name) {
            try {
                List<Categorie> selectedCate;

                if (Session["selectedCategorie"] != null) {
                    selectedCate = (List<Categorie>) Session["selectedCategorie"];
                }
                else {
                    selectedCate = new List<Categorie>();
                }

                Categorie c = new Categorie {
                    Nom = name
                };

                selectedCate.Add(c);
                Session["selectedCategorie"] = selectedCate;
            }
            catch (Exception e) {
                logger.Error(e);
            }
        }

        /// <summary>
        /// Supprime une catégorie dans la variable de session qui sera
        /// utilisée pour la création de la compétition
        /// </summary>
        /// <param name="name">Catégorie à supprimer</param>
        public void DelCategorie(string name, string competName) {
            Contract.Requires(Session["selectedCategorie"] != null,
                               "La variable de session ne devrait pas être vide à cet endroit du code");
            try {
                List<Categorie> selectedCate;

                if (Session["selectedCategorie"] != null) {
                    selectedCate = (List<Categorie>) Session["selectedCategorie"];
                }
                else {
                    //Ne devrait jamais se produire
                    Competition c = Competition.GetByName(competName);
                    selectedCate = c.Categorie.ToList();
                }

                Categorie cate = selectedCate.Where(d => d.Nom == name).SingleOrDefault();
                if (cate != null) {
                    selectedCate.Remove(cate);
                }

                Session["selectedCategorie"] = selectedCate;
            }
            catch (Exception e) {
                logger.Error(e);
            }
        }

        private List<Competition> GetCompetitions() {
            //Used to init the Categorie dropdown list
            ViewBag.CateList = GetCateList();
            List<Competition> compets = Competition.GetAll();
            return compets;

        }

        /// <summary>
        /// Récupère la liste des catégories pour les afficher
        /// </summary>
        /// <param name="excluded">Catégories déjà sélectionnées
        /// à exclure de la liste</param>
        /// <returns></returns>
        private List<string> GetCateList(List<Categorie> excluded = null) {
            List<String> cateList = Categorie.GetAll().Select(d => d.Nom).ToList();

            if (excluded != null) {
                List<string> selectedCate = excluded.Select(d => d.Nom).ToList();
                cateList.RemoveAll(d => selectedCate.Contains(d));
            }

            return cateList;
        }

        #region Json Reporting
        /// <summary>
        /// Retourne le nombre de participant par catégorie d'age
        /// </summary>
        /// <param name="id">Compétition id</param>
        /// <returns></returns>
        public JsonResult PieCategorie(int id) {
            //Competition compet = Competition.GetById(id);
            List<Competiteur> competiteurs = Inscriptions.GetInscriptions(id);
            var res = from c in competiteurs
                      group c by c.Categorie.Nom into g

KarateIsere/KarateIsere/Areas/Private/Views/Competitions/Create.cshtml
@model KarateIsere.DataAccess.Competition
@using KarateIsere.DataAccess;
@{
    //Truc et astuce pour pouvoir utiliser la vue "Create" pour create et edit
    string action = ViewContext.RouteData.GetRequiredString("action");
    if (action != "Edit") {
        action = "Create";
    }
}

@using (Html.BeginForm(@action, "Competitions", FormMethod.Post)) {
    @Html.AntiForgeryToken()

    if (action == "Edit") { 
        @Html.HiddenFor(model=>model.CompetitionID)
    }
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new {
       @class = "text-danger"
   })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new {
           @class = "control-label col-md-2"
       })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new {
               htmlAttributes = new {
                   @class = "form-control"
               }
           })
                @Html.ValidationMessageFor(model => model.Nom, "", new {
               @class = "text-danger"
           })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCompetition, htmlAttributes: new {
           @class = "control-label col-md-2"
       })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCompetition, new {
               htmlAttributes = new {
                   @class = "form-control",
                   placeholder = "Choisissez une date",
               }
           })

                @Html.ValidationMessageFor(model => model.DateCompetition, "", new {
               @class = "text-danger"
           })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinInscription, htmlAttributes: new {
           @class = "control-label col-md-2"
       })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinInscription, new {
               htmlAttributes = new {
                   @class = "form-control",
               }
           })
                @Html.ValidationMessageFor(model => model.FinInscription, "", new {
               @class = "text-danger"
           })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lieu, htmlAttributes: new {
           @class = "control-label col-md-2"
       })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lieu, new {
               htmlAttributes = new {
                   @class = "form-control"
               }
           })
                @Html.ValidationMessageFor(model => model.Lieu, "", new {
               @class = "text-danger"
           })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsKata, htmlAttributes: new {
           @class = "control-label col-md-2"
       })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsKata)
                    @Html.ValidationMessageFor(model => model.IsKata, "", new {
                   @class = "text-danger"
               })
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h5>Liste des catégories</h5>
                    </div>
                </div>
                <div class="panel-body"
                     dropzone="true" ondrop="dropRemove(event)" ondragover="allowDrop(event)">
                    <ul id="dropSrc">
                        @if (ViewBag.CateList != null) {
                            foreach (var item in ViewBag.CateList) {
                                <li id="@item" draggable="true" ondragstart="drag(event)">@item</li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h5>Glissez et déposez les catégories sélectionnées</h5>
                    </div>
                </div>

                <div class="panel-body"
                     dropzone="true" ondrop="dropAdd(event)" ondragover="allowDrop(event)">

                    <ul id="dropDest">
                        @if (Model != null && Model.Categorie != null) {
                            foreach (Categorie item in Model.Categorie) {
                                <li id="@item.Nom" draggable="true" ondragstart="drag(event)">@item.Nom</li>
                            }
                        }
                    </ul>

                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="form-groupcol-md-12">
            <div class="col-md-offset-5">
                @if (@action == "Edit") {
                    <input type="submit" value="Modifier" class="btn btn-default" />
                }
                else {

                    <input type="submit" value="Créer" class="btn btn-default" />
                }
            </div>
        </div>
    </div>
}


<script>
    function allowDrop(ev) {
        ev.preventDefault();
    }

    function drag(ev) {
        console.log("drag" + ev);
        ev.dataTransfer.setData("text/html", ev.target.id);
    }

    function dropAdd(ev) {
        console.log("drop" + ev);
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text/html");
        console.log(data);
        console.log(ev.target);
        // ev.target.appendChild(document.getElementById(data));

        $.ajax({
            type: "POST",
            url: "@Url.Action( "AddCategorie","Competitions" )",
            data: { name: data },
            success: function (res) {
                $("#dropDest").append(document.getElementById(data));
            }
        });
    }

    function dropRemove(ev) {
        console.log("dropRemove" + ev);
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text/html");
        console.log(data);
        console.log(ev.target);

        $.ajax({
            type: "POST",
            url: "@Url.Action( "DelCategorie","Competitions" )",
            data: { name: data },
            success: function (res) {
                $("#dropSrc").append(document.getElementById(data));
            }
        });

    }

    $('.datepicker').datepicker({
        //format: 'dd/mm/yyyy',
        startDate: '9m',
        language: 'fr'
    })
</script>

KarateIsere/KarateIsere/Areas/Private/Views/Competitions/Details.cshtml
@model IEnumerable<KarateIsere.DataAccess.Competiteur>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Retour", "Index")
</p>

<div id="pieCate" style="width: 300px; height: 150px;" class="pull-left">
</div>

<div id="pieSexe" style="width: 300px; height: 150px;" class="pull-left">
</div>

<div class="clearfix"></div>
<div>
    <table class="table-condensed ">
        <tr>
            <td>
                @Html.ActionLink("Exporter", "Export", new { id = ViewBag.CompetId }, new { @class = "btn btn-default" })
            </td>
            <td>
                @Ajax.ActionLink("Envoyer rappel", "NotifyNonInscrits",
                new { id = ViewBag.CompetId },
                new AjaxOptions {
                    OnBegin="NotificationStart",
                    OnSuccess="NotificationSuccess",
                    OnFailure="NotificationFailed",
                    InsertionMode = System.Web.Mvc.Ajax.InsertionMode.Replace,
                    UpdateTargetId = "notifyRes"
                },
                new { @class = "btn btn-default", id = "NotifyEmail" }
                )
            </td>

        </tr>
    </table>

    <table class="table">
        <tr>
            <th>
                Catégorie
            </th>
            <th>
                Club
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poids)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isHomme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumLicence)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Categorie.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Club.NomClub)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prenom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Poids)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isHomme)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumLicence)
                </td>
                <!--<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.NumLicence }) |
                    @Html.ActionLink("Details", "Details", new { id = item.NumLicence }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.NumLicence })
                </td>
                    -->
            </tr>
        }

    </table>

</div>



<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script src="~/js/EmailNotification.js"></script>

<script>
    //Display pie charts
    function DrawStatistics() {

        var Draw = {
            init: function () {
                this.PieCategorie('@Url.Action("PieCategorie", new { id =       ViewBag.CompetId })',
                   "Catégories",
                   "Categorie",
                   "pieCate");
                this.PieCategorie('@Url.Action("PieSexe", new { id = ViewBag.CompetId })',
                        "Sexe",
                        "Sexe",
                        "pieSexe");
            },

            PieCategorie: function (url, titre, colName, targetDiv) {
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    contentType: 'application/json',
                    url: url,
                    data: '{}',
                    success: function (chartsdata) {

                        // Callback that creates and populates a data table,
                        // instantiates the pie chart, passes in the data and
                        // draws it.

                        var data = new google.visualization.DataTable();
                        data.addColumn('string', colName);
                        data.addColumn('number', 'Count');

                        for (var i = 0; i < chartsdata.length; i++) {
                            data.addRow([chartsdata[i][colName], chartsdata[i].Count]);
                        }

                        // Instantiate and draw our chart, passing in some options
                        var chart = new google.visualization.PieChart(document.getElementById(targetDiv));

                        chart.draw(data,
                          {
                              title: titre,
                              position: "top",
                              fontsize: "14px",
                              chartArea: { width: '100%' },
                          });
                    },
                    error: function () {
                        alert("Error lors du chargement des données.");
                    }
                });
            },
        }

        Draw.init();
    };

    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(DrawStatistics);
</script>

KarateIsere/KarateIsere/Areas/Private/Views/Competitions/Edit.cshtml
@model KarateIsere.DataAccess.Competition

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>



@Html.Partial( "Create", @Model )
<div>
    @Html.ActionLink("Retour", "Index")
</div>

KarateIsere/KarateIsere/Areas/Private/Views/Competitions/Index.cshtml
@model IEnumerable<KarateIsere.DataAccess.Competition>
@using KarateIsere.DataAccess;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gestion des compétitions</h2>
<hr />

    <div class="panel panel-default" id="panel1">
        <div class="panel-heading">
            <div class="panel-title">
                <a data-toggle="collapse" data-target="#collapseOne"
                   href="#collapseOne">
                    <h4>Créer une nouvelle compétition</h4>
                </a>
            </div>
        </div>
        <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
                @Html.Partial( "Create", new Competition())
            </div>
        </div>
    </div>


<br/>

<div class="panel panel-default">

    <div class="panel-heading">
            <div class="panel-title">
                <h4>Liste des compétitions</h4>
            </div>
    </div>

    <div class="panel-body">
        @if (Model != null) {

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor( model => model.DateCompetition )
                    </th>
                    <th>
                        @Html.DisplayNameFor( model => model.Nom )
                    </th>
                    <th>
                        @Html.DisplayNameFor( model => model.FinInscription )
                    </th>
                    <th>
                        @Html.DisplayNameFor( model => model.Lieu )
                    </th>
                    <th>
                        @Html.DisplayNameFor( model => model.IsKata )
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model) {
                    <tr>                     
                        <td>
                            @Html.DisplayFor( modelItem => item.DateCompetition )
                        </td>
                        <td>
                            @Html.ActionLink(item.Nom, "Details", new { id = item.CompetitionID })
                        </td>
                        <td>
                            @Html.DisplayFor( modelItem => item.FinInscription )
                        </td>
                        <td>
                            @Html.DisplayFor( modelItem => item.Lieu )
                        </td>
                        <td>
                            @Html.DisplayFor( modelItem => item.IsKata )
                        </td>
                        <td>
                            @Html.ActionLink( "Edit", "Edit", new {
                           competId=item.CompetitionID
                       } ) @*|
                            @Html.ActionLink( "Details", "Details", new {
                           id=item.Nom
                       } )*@ |
                            @Html.ActionLink( "Delete", "Delete", new {
                           competId = item.CompetitionID
                       } ) 
                        </td>
                    </tr>
                }

            </table>
        }
    </div>

</div>