KarateIsere/KarateIsere/Areas/Private/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KarateIsere.DataAccess;
using NLog;

namespace KarateIsere.Areas.Private.Controllers {
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller {
        Logger log = LogManager.GetCurrentClassLogger();

        // GET: Private/Categories
        public ActionResult Index () {
            try {
                InitCategorie();
            }
            catch (Exception e) {
                log.Error(e);
            }
            return View();
        }

        // GET: Private/Categories/Details/5
        public ActionResult Details ( int id ) {
            return View();
        }

        [HttpPost]
        public ActionResult Create ( Categorie cate ) {
            try {
                if (ModelState.IsValid) {
                    cate.Create();
                    return RedirectToAction("Index");
                }

                InitCategorie();
            }
            catch (Exception e) {
                log.Error(e);
            }

            return View("Index",cate);
        }

        public ActionResult Delete ( string nomCate ) {
            try {
                Categorie c = new Categorie {
                    Nom = nomCate
                };

                c.Delete();              
            }
            catch (Exception e) {
                log.Error(e);
            }

            return RedirectToAction("Index");
        }

        private void InitCategorie() {
            List<Categorie> cates = Categorie.GetAll();
            ViewBag.Categories = cates;
        }
    }
}

KarateIsere/KarateIsere/Areas/Private/Controllers/CompetiteursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KarateIsere.DataAccess;
using KarateIsere.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using NLog;

namespace KarateIsere.Areas.Private.Controllers {
    [Authorize(Roles = "User")]
    public class CompetiteursController : Controller {
        private ApplicationUserManager _userManager;
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public ApplicationUserManager UserManager {
            get {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set {
                _userManager = value;
            }
        }

        // GET: Private/Competiteurs
        public ActionResult Index() {
            if (Session["User"] != null) {
                try {
                    Init();
                }
                catch (Exception e) {
                    logger.Error(e);
                }

                return View();
            }
            else {
                return RedirectToAction("login", "Account", new {
                    area = "",
                    ReturnUrl = HttpContext.Request.Url.ToString()
                });
            }
        }

        private ApplicationUser Init() {
            ApplicationUser appUser = (ApplicationUser) Session["User"];
            Club c = appUser.Club;
            c = Club.Get(c.NumAffiliation);
            ViewBag.Categories = GetCategorieList();
            ViewBag.Competiteurs = c.Competiteur.ToList();

            return appUser;
        }

        private List<SelectListItem> GetCategorieList() {
            List<Categorie> cList = Categorie.GetAll();
            List<SelectListItem> res = new List<SelectListItem>();

            foreach (Categorie c in cList) {
                SelectListItem sli = new SelectListItem();
                sli.Text = c.Nom;
                sli.Value = c.CategorieID.ToString();
                res.Add(sli);
            }

            return res;
        }

        // POST: Private/Competiteurs/Create
        [HttpPost]
        public ActionResult Create(Competiteur competiteur) {
            try {
                if (ModelState.IsValid) {                    
                    competiteur.Create();
                    return RedirectToAction("Index");
                }
                else {
                    Init();
                    return View("Index", competiteur);
                }
            }
            catch (Exception e) {
                logger.Error(e);
                return View("Index");
            }
        }

        // GET: Private/Competiteurs/Edit/5
        public ActionResult Edit(string id) {
            Competiteur c = new Competiteur();

            try {
                c = Competiteur.Get(id);
                ViewBag.Categories = GetCategorieList();
            }
            catch (Exception e) {
                logger.Error(e);
            }

            return View(c);
        }

        // POST: Private/Competiteurs/Edit/5
        [HttpPost]
        public ActionResult Edit(Competiteur c) {
            try {
                c.Update();
                //ViewBag.Categories = GetCategorieList();
                return RedirectToAction("Index");
            }
            catch (Exception e) {
                logger.Error(e);
                return View();
            }
        }

        // GET: Private/Competiteurs/Delete/5
        public ActionResult Delete(string id) {
            try {
                Competiteur c = new Competiteur();
                c.NumLicence = id;
                // Delete cascade on a compétiteur delete
                c.Delete();
                return RedirectToAction("Index");
            }
            catch (Exception e) {
                logger.Error(e);
                return View();
            }
        }
    }
}

KarateIsere/KarateIsere/Areas/Private/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KarateIsere.DataAccess;
using NLog;


namespace KarateIsere.Areas.Private.Controllers {
    [Authorize(Roles = "Admin")]

    public class RoleController : Controller {

        Logger log = LogManager.GetCurrentClassLogger();

        // GET: Private/Role
        public ActionResult Index() {
            Role r = new Role();
            List<string> roles = r.Get().Select(d => d.Name).ToList();
            ViewBag.Roles = roles;
            return View();
        }

        // POST: Private/Role/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection) {
            try {
                // TODO: Add insert logic here
                string roleName = collection["roleName"].ToString();
                Role r = new Role(roleName);
                r.Create();
                return RedirectToAction("Index");
            }
            catch {
                return View();
            }
        }

        // GET: Private/Role/Delete/5
        public ActionResult Delete(string id) {
            try {
                Role r = new Role(id);
                r.Delete();
            }
            catch (Exception e) {
                log.Error(e);
            }

            return RedirectToAction("Index");
        }
    }
}

KarateIsere/KarateIsere/Areas/Public/Controllers/ClubMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoogleAPI.Maps.Services;
using Model = GoogleAPI.Maps.Model;
using GoogleAPI.Maps.Model.Geocoding;
using KarateIsere.DataAccess;
using Newtonsoft.Json;
using NLog;

namespace KarateIsere.Areas.Public.Controllers {
    public class ClubMapController : Controller {
        Logger log = LogManager.GetCurrentClassLogger();

        // GET: Public/ClubMap
        public ActionResult Carte() {
            try {
                List<Club> clubs = Club.GetAll();
                UpdateCoordonne(clubs);
                string json = JsonConvert.SerializeObject(clubs);
                ViewBag.ClubInfos = json;
            }
            catch (Exception e) {
                log.Error(e);
            }

            return View("Carte");
        }

        public ActionResult Index() {
            List<Club> clubs = new List<Club>();
            try {
                clubs = Club.GetAll();
            }
            catch (Exception e) {
                log.Error(e);
            }
            return View(clubs);
        }

        private void UpdateCoordonne(List<Club> clubs) {
            Geocoding geocode = new Geocoding();

            foreach (Club c in clubs) {
                if (!c.Latitude.HasValue || c.Latitude == 0 ||
                    !c.Longitude.HasValue || c.Longitude == 0) {

                    // on rappelle update pour réexecuter la logique de mise à jour
                    // des coordonnées
                    c.Update();                   
                }
            }
        }
    }
}

KarateIsere/KarateIsere/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

KarateIsere/KarateIsere/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

KarateIsere/KarateIsere/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CDI</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Gridmvc.css")
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/site.css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/bootstrap-datepicker.css")
    @Styles.Render("~/Content/bootstrap-datepicker3.css")


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.js")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Karaté Isère", "Index", "Home", new {
               area = ""
           }, new {
               @class = "navbar-brand"
           })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clubs <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                           
      <li>
         @Html.ActionLink("Carte des clubs", "Carte", "ClubMap", new {
        area = "Public"
    }, null)
     </li>
                        

     <li>
         @Html.ActionLink("Liste des clubs", "Index", "ClubMap", new {
        area = "Public"
    }, null)
     </li>
                      
                            @if (HttpContext.Current.User.IsInRole("User")) {
                                <!-- Section used only for authenticated user managing a club-->
                            <li>
                                @Html.ActionLink("Compétiteurs", "Index", "Competiteurs", new {
                                   area = "Private"
                               }, null)
                            </li>
                            <li>
                                @Html.ActionLink("Inscriptions", "Index", "Inscriptions", new {
                                   area = "Private"
                               }, null)
                            </li>
                            }
                        </ul>
                    </li>

                   <!-- <li>
                        @Html.ActionLink("À propos de", "About", "Home", new {
                       area = ""
                   }, null)
                    </li>
                       -->

                    <li>
                        @Html.ActionLink("Contact", "Contact", "Home", new {
                       area = ""
                   }, null)
                    </li>

                    @if (HttpContext.Current.User.IsInRole("Admin")) {
                        //Section accessible only for the administrator
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                @Html.ActionLink("Catégories", "Index", "Categories", new {
                                   area = "Private"
                               }, null)
                            </li>
                            <li>
                                @Html.ActionLink("Compétitions", "Index", "Competitions", new {
                                   area = "Private"
                               }, null)
                            </li>
                            <li>
                                @Html.ActionLink("Ajouter Roles", "Index", "Role", new {
                                   area = "Private"
                               }, null)
                            </li>
                            <li>
                                @Html.ActionLink("Ajouter Administrateur", "Index", "Admin", new {
                                   area = "Private"
                               }, null)
                            </li>
                        </ul>
                    </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <noscript>
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                JavaScript est désactivé, ce site web ne fonctionnera pas correctement.
                Pour activer l'utilisation de JavaScript vous pouvez vous référer au guide suivant :

                <a href="http://www.enable-javascript.com/fr/#chrome" target="_blank">Activer JavaScript dans votre navigateur</a>
            </div>
        </noscript>

        <div id="notifyRes" class="alert alert" role="alert" hidden></div>

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comité Départemental de l'Isère</p>
        </footer>
    </div>



    @Scripts.Render("~/Scripts/gridmvc.min.js")
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")" type="text/javascript"> </script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>