KarateIsere/KarateIsere/Areas/Private/Controllers/CompetiteursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KarateIsere.DataAccess;
using KarateIsere.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using NLog;

namespace KarateIsere.Areas.Private.Controllers {
    [Authorize(Roles = "User")]
    public class CompetiteursController : Controller {
        private ApplicationUserManager _userManager;
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public ApplicationUserManager UserManager {
            get {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set {
                _userManager = value;
            }
        }

        // GET: Private/Competiteurs
        public ActionResult Index() {
            if (Session["User"] != null) {
                try {
                    Init();
                }
                catch (Exception e) {
                    logger.Error(e);
                }

                return View();
            }
            else {
                return RedirectToAction("login", "Account", new {
                    area = "",
                    ReturnUrl = HttpContext.Request.Url.ToString()
                });
            }
        }

        private ApplicationUser Init() {
            ApplicationUser appUser = (ApplicationUser) Session["User"];
            Club c = appUser.Club;
            c = Club.Get(c.NumAffiliation);
            ViewBag.Categories = GetCategorieList();
            ViewBag.Competiteurs = c.Competiteur.ToList();

            return appUser;
        }

        private List<SelectListItem> GetCategorieList() {
            List<Categorie> cList = Categorie.GetAll();
            List<SelectListItem> res = new List<SelectListItem>();

            foreach (Categorie c in cList) {
                SelectListItem sli = new SelectListItem();
                sli.Text = c.Nom;
                sli.Value = c.CategorieID.ToString();
                res.Add(sli);
            }

            return res;
        }

        // POST: Private/Competiteurs/Create
        [HttpPost]
        public ActionResult Create(Competiteur competiteur) {
            try {
                if (ModelState.IsValid) {                    
                    competiteur.Create();
                    return RedirectToAction("Index");
                }
                else {
                    Init();
                    return View("Index", competiteur);
                }
            }
            catch (Exception e) {
                logger.Error(e);
                return View("Index");
            }
        }

        // GET: Private/Competiteurs/Edit/5
        public ActionResult Edit(string id) {
            Competiteur c = new Competiteur();

            try {
                c = Competiteur.Get(id);
                ViewBag.Categories = GetCategorieList();
            }
            catch (Exception e) {
                logger.Error(e);
            }

            return View(c);
        }

        // POST: Private/Competiteurs/Edit/5
        [HttpPost]
        public ActionResult Edit(Competiteur c) {
            try {
                c.Update();
                //ViewBag.Categories = GetCategorieList();
                return RedirectToAction("Index");
            }
            catch (Exception e) {
                logger.Error(e);
                return View();
            }
        }

        // GET: Private/Competiteurs/Delete/5
        public ActionResult Delete(string id) {
            try {
                Competiteur c = new Competiteur();
                c.NumLicence = id;
                // Delete cascade on a compétiteur delete
                c.Delete();
                return RedirectToAction("Index");
            }
            catch (Exception e) {
                logger.Error(e);
                return View();
            }
        }
    }
}

KarateIsere/KarateIsere/Areas/Private/Controllers/InscriptionsController.cs
using KarateIsere.DataAccess;
using KarateIsere.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLog;

namespace KarateIsere.Areas.Private.Controllers {
    [Authorize(Roles="User")]
    public class InscriptionsController : Controller {
        Logger log = LogManager.GetCurrentClassLogger();

        // GET: Private/Inscriptions
        public ActionResult Index() {
            try {
                ApplicationUser club = (ApplicationUser) Session["User"];
                ViewBag.Competition = ToSelectItem(Competition.GetActive());

                List<Competiteur> dejaInscr = new List<Competiteur>();
                List<Competiteur> competiteur = new List<Competiteur>();

                if (Session["selectedCompetition"] != null) {
                    int competitionId = Convert.ToInt32(Session["selectedCompetition"]);
                    dejaInscr = GetInscrits(club, competitionId);
                    competiteur = GetCompetiteurs(club.NumAffiliation, dejaInscr, competitionId);
                }
                else {
                    competiteur = Competiteur.GetCompetitieurs(club.NumAffiliation);
                }

                ViewBag.Inscrits = dejaInscr;
                Session["SelectedCompetiteurs"] = dejaInscr.Select(d => d.NumLicence).ToList();
                ViewBag.Competiteurs = competiteur;
            }
            catch (Exception e) {
                log.Error(e);
            }
            return View();
        }

        /// <summary>
        /// Retourne la liste de inscrits à la compétition
        /// </summary>
        /// <param name="club">Numéro d'affiliation du club</param>
        /// <param name="competitionId">Compétition Id</param>
        /// <returns>La liste des inscrits ou une liste vide</returns>
        private List<Competiteur> GetInscrits(ApplicationUser club, int competitionId) {
            List<Competiteur> inscrits = new List<Competiteur>();
            List<Inscriptions> inscr = Inscriptions.GetClubInscriptions(competitionId, club.NumAffiliation);

            //Get les compétieurs à partir de leur numéro de licence
            foreach (Inscriptions i in inscr) {
                inscrits.Add(Competiteur.Get(i.NumLicence));
            }

            return inscrits;
        }

        /// <summary>
        /// Retourne la liste des compétiteurs n'étant pas inscrits à la compétition
        /// </summary>
        /// <param name="numAffClub">Numéro d'affiliation du club</param>
        /// <param name="exclude">Liste des compétiteurs déjà inscrits</param>
        /// <returns>Liste de compétiteur ou null</returns>
        private List<Competiteur> GetCompetiteurs(string numAffClub, List<Competiteur> exclude,int competitionId) {
            //Exclue les compétiteurs qui sont déjà inscrits
            List<Competiteur> res = Competiteur.GetCompetitieurs(numAffClub);
            res.RemoveAll(d => exclude.Any(
                                e => e.NumLicence == d.NumLicence
                                )
                         );

            //Exclue les compétiteurs qui ne sont pas dans les catégories de la compétition
            Competition compet = Competition.GetById(competitionId);
            List<int> categoriIds = compet.Categorie.Select(d => d.CategorieID).ToList();
            res = res.Where(d => categoriIds.Contains(d.CategorieID)).ToList();

            return res;
        }

        private List<SelectListItem> ToSelectItem(List<Competition> list) {
            List<SelectListItem> res = new List<SelectListItem>();
            if (list != null) {
                foreach (Competition c in list) {
                    SelectListItem sli = new SelectListItem {
                        Text = c.Nom,
                        Value = c.CompetitionID.ToString()
                    };

                    if (Session["selectedCompetition"] != null &&
                       Convert.ToInt32(Session["selectedCompetition"]) == c.CompetitionID) {
                        sli.Selected = true;
                    }

                    res.Add(sli);
                }     
            }

            if (Session["selectedCompetition"] == null && res.Count > 0) {
                SelectListItem first = res.First();
                first.Selected = true;
                Session["selectedCompetition"] = first.Value;
            }

            return res;
        }

        public void AddCompetiteur(string numLicence) {
            try {
                List<string> selLicences;
                if (Session["SelectedCompetiteurs"] != null) {
                    selLicences = (List<string>) Session["SelectedCompetiteurs"];
                }
                else {
                    selLicences = new List<string>();
                }

                selLicences.Add(numLicence);
                Session.Add("SelectedCompetiteurs", selLicences);
            }
            catch (Exception e) {
                log.Error(e);
            }
        }

        public void DelCompetiteur(string numLicence) {
            try {
                List<string> selLicences;
                if (Session["SelectedCompetiteurs"] != null) {
                    selLicences = (List<string>) Session["SelectedCompetiteurs"];
                }
                else {
                    selLicences = new List<string>();
                }

                selLicences.Remove(numLicence);
                Session.Add("SelectedCompetiteurs", selLicences);
            }
            catch (Exception e) {
                log.Error(e);
            }
        }

        public void SetCompetition(string competId) {
            Session["selectedCompetition"] = competId;
        }

        // GET: Private/Inscriptions/Create
        public ActionResult Create() {
            //ViewBag.Competition = ToSelectItem(Competition.GetActive());
            return View();
        }

        // POST: Private/Inscriptions/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection) {
            try {
                ApplicationUser club = (ApplicationUser) Session["User"];
                int competitionId = Convert.ToInt32(collection["CompetitionId"]);
                List<string> selCompetiteurs = null;
                List<Inscriptions> inscriptions = new List<Inscriptions>();
                List<Competiteur> dejaInscr = GetInscrits(club, competitionId);

                if (Session["SelectedCompetiteurs"] != null) {
                    selCompetiteurs = (List<string>) Session["SelectedCompetiteurs"];

                    //Create inscription
                    foreach (string numAff in selCompetiteurs) {
                        Inscriptions i = new Inscriptions();
                        i.CompetitionID = competitionId;
                        i.NumLicence = numAff;

                        //Si l'inscription n'existe pas alors la créé
                        if (!dejaInscr.Any(d => d.NumLicence == numAff)) {
                            i.Create();
                        }
                    }

                    //Delete inscription
                    foreach (Competiteur c in dejaInscr) {
                        if (!selCompetiteurs.Contains(c.NumLicence)) {
                            Inscriptions i = new Inscriptions();
                            i.CompetitionID = competitionId;
                            i.NumLicence = c.NumLicence;
                            i.Delete();
                        }
                    }
                }

                // TODO: Add insert logic here
                return RedirectToAction("Index");
            }
            catch (Exception e) {
                log.Error(e);
                return View();
            }
        }
    }
}

KarateIsere/KarateIsere/Areas/Private/Views/Inscriptions/Create.cshtml
@model KarateIsere.DataAccess.Inscriptions
@using KarateIsere.DataAccess;



@using (Html.BeginForm("Create", "Inscriptions", FormMethod.Post)) {
    @Html.AntiForgeryToken()
    List<Competiteur> competiteurs = (List<Competiteur>) ViewBag.Competiteurs;
    List<Competiteur> inscrits = (List<Competiteur>) ViewBag.Inscrits;
    List<SelectListItem> competitions = (List<SelectListItem>) ViewBag.Competition;

    if (competitions != null && competitions.Count > 0) {
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new {
       @class = "text-danger"
   })

            <div class="form-group col-md-12">
                <label class="control-label col-md-4"> Sélectionnez une compétition</label>
                <div class="col-md-8">
                    @Html.DropDownListFor(Model => Model.CompetitionID, competitions, htmlAttributes: new {
               @class = "form-control",
               @onchange = "setCompetId(this.value)"
           })
                </div>
            </div>



            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>Vos compétiteurs</h4>
                        </div>
                    </div>

                    <div class="panel-body" dropzone="true" ondragover="allowDrop(event)"
                         ondrop="dropRemove(event)">
                        @if ((competiteurs != null && competiteurs.Count > 0)
                        || (inscrits != null && inscrits.Count > 0)) {
                            <div class="panel-body">
                                <table id="dropSrc" class="table">
                                    @foreach (Competiteur c in competiteurs) {

                                        <tr id="@c.NumLicence" draggable="true" ondragstart="drag(event)">
                                            <td>
                                                @Html.Label(@c.NumLicence)
                                            </td>
                                            <td>
                                                @Html.Label(@c.Nom)
                                            </td>
                                            <td>
                                                @Html.Label(@c.Prenom)
                                            </td>
                                            <td>
                                                @Html.Label(@c.Categorie.Nom)
                                            </td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        }
                        else {
                                <p>
                                    Vous n'avez pas de compétiteurs enregistrés. @Html.ActionLink("Ajouter des compétiteurs", "Index", "Competiteurs", new {
                                                                        area = "Private"
                                                                    }, null)
                                </p>
                        }
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>Listes des inscrits</h4>
                        </div>
                    </div>

                    <div class="panel-body" dropzone="true" ondrop="dropAdd(event)" ondragover="allowDrop(event)"
                         ondragstart="drag(event)">
                        <table id="dropDest" class="table">

                            @foreach (Competiteur c in inscrits) {

                                <tr id="@c.NumLicence" draggable="true" ondragstart="drag(event)">
                                    <td>
                                        @Html.Label(@c.NumLicence)
                                    </td>
                                    <td>
                                        @Html.Label(@c.Nom)
                                    </td>
                                    <td>
                                        @Html.Label(@c.Prenom)
                                    </td>
                                    <td>
                                        @Html.Label(@c.Categorie.Nom)
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>
            </div>

            <div>
                <input type="submit" value="Sauver" class="btn btn-default" />
            </div>
        </div>
    }
    else {
        <div>
            <p>Il n'y a pas encore de compétitions créées pour cette années.</p>
        </div>
    }
}



<script>
    function allowDrop(ev) {
        ev.preventDefault();
    }

    function drag(ev) {
        console.log("drag" + ev.target.id);
        ev.dataTransfer.setData("text/html", ev.target.id);
    }

    function dropAdd(ev) {
        console.log("drop" + ev);
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text/html");
        console.log('dropAdd : ' + data);
        console.log(ev.target);
        // ev.target.appendChild(document.getElementById(data));

        $.ajax({
            type: "POST",
            url: "@Url.Action( "AddCompetiteur", "Inscriptions" )",
            data: { numLicence: data },
            success: function (res) {
                $("#dropDest").append(document.getElementById(data));
            }
        });
    }

    function dropRemove(ev) {
        console.log("dropRemove" + ev);
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text/html");
        console.log(data);
        console.log(ev.target);

        $.ajax({
            type: "POST",
            url: "@Url.Action( "DelCompetiteur", "Inscriptions" )",
            data: { numLicence: data },
            success: function (res) {
                $("#dropSrc").append(document.getElementById(data));
            }
        });
    }

    function setCompetId(competId) {
        $.ajax({
            type: "POST",
            url: "@Url.Action( "SetCompetition", "Inscriptions" )",
            data: { competId: competId },
            success: function () {
                window.location = '@Url.Action("Index", "Inscriptions")';
            }
        });
    }
</script>

KarateIsere/KarateIsere/Areas/Private/Views/Inscriptions/Index.cshtml
@model IEnumerable<KarateIsere.DataAccess.Inscriptions>

@{
    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inscriptions aux compétitions</h2>
<hr />
<p>
    @Html.Partial("Create")
</p>